exclude: "^docs/|/migrations/|/hooks/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: requirements-txt-fixer
        files : (requirements|requirements_kuona|requirements_deploy)\.txt$

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.12.0
#    hooks:
#      - id: ruff-check
#        args: [ --fix, --ignore, D ]
#        types_or: [ python, pyi ]
#      - id: ruff-format
